### ISSUE TITLE
no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by blauhorn** [developeregrem/pve-dockerized#5]
Hallo,

ich hatte fewohbee auf einem raspberry pi 4 schonmal am Laufen, und wollte mich etwas reinarbeiten. Dann habe ich irgendein Update gefahren, und dann lief es nicht mehr. Nun hatte ich etwas Zeit und wollte reanimieren, geht aber nicht.
Es kommt bei drei Paketen aus der docker-compose dieser Fehler:
`no matching manifest for linux/arm/v7 in the manifest list entries`
Die db habe ich inzwischen hinbekommen, aber php und acme machen nicht mit. Auf dem raspi läuft ein debian 11(bullseye).
Weiß jemand eine Lösung?

**Comment by developeregrem** [comment]
Hi @blauhorn 
führe auf dem raspi bitte einmal `dpkg --print-architecture` aus und schaue, ob deine CPU Architektur bei den von mir angebotenen prebuild images dabei ist: [PHP architectures](https://github.com/developeregrem/fewohbee-phpfpm?tab=readme-ov-file#supported-architectures)
Den Support für 32bit Prozessoren habe ich vor einiger Zeit entfernt, möglich das es daran liegt.
Wenn du es zum Laufen bekommen willst, müsstest du die repos für [php](https://github.com/developeregrem/fewohbee-phpfpm) und [acme](https://github.com/developeregrem/fewohbee-acme) lokal clonen und dann mit `docker build` selbst bauen.
Also z.B.
```
git clone https://github.com/developeregrem/fewohbee-phpfpm.git
cd fewohbee-phpfpm
docker build -t developeregrem/fewohbee-phpfpm:latest .
```
und das Gleiche für [acme](https://github.com/developeregrem/fewohbee-acme) (tag im letzten Befehl entsprechend anpassen).
Danach sollte es eigentlich gehen, da er dann deine lokalen images nimmt.

**Comment by blauhorn** [comment]
Vielen Dank, es ist armhf. Daran liegt's also. Ich versuche das selbst zu bauen, und informiere hier über den Fortschritt.

**Comment by blauhorn** [comment]
Ich habe es offenbar nicht richtig verstanden. Hatte gestern versucht, das selbst zu bauen, aber beim build des acme läuft der Prozess mehrere Stunden 
`Building wheel for cryptography (pyproject.toml)`
Das musste ich dann doch abbrechen, da ich den Pi noch für andere Zwecke laufen habe, die dann lahmgelegt sind.
Ich habe aber dann jetzt nochmal nach der Architektur vom OS geguckt, die Abfrage von
`uname -a`
bringt jedenfalls 
`Linux lms 6.1.21-v8+ ..... aarch64`
Also ist es doch 64bit. Was verstehe ich hier nicht?
Wär ganz lieb, wenn Du mir nochmal einen Tipp geben könntest.

**Comment by developeregrem** [comment]
Hi, die CPU ist hier ausschlaggebend. Schau mal was bei `cat /proc/cpuinfo` steht. Ich vermute da steht ARMv7 bei model name. Erst ab v8 gab es 64 bit support.

**Comment by blauhorn** [comment]
Okay, danke für den Hinweis. Das Problem steckt wahrscheinlich tiefer, das will ich Dir jetzt nicht weiter zumuten. Es wird gar kein model angezeigt, lediglich bei "Hardware" zeigt es BCM2835. Meine Recherchen ergaben, dass der Kernel bei diesen Boards (Raspberry Pi 4 Model B Rev. 1.1) offenbar die Abfrage falsch beantwortet. 

Ich habe zum Probieren die Software jetzt erstmal auf meinem PC installiert und werde wohl für den Produktivbetrieb einen neueren Raspi beschaffen. Vielen Dank für Deine Hilfe und für die tolle Arbeit, die Du in die Software gesteckt hast.
